EXEC=app
SRCS=$(wildcard *.c) 
ASRC=$(wildcard *.s)

#specifiy additional packages to build
EXTRADIRS=images

# Includee the standard APF27 makefile for the microprocessor labs 
include $(LMIBASE)/apf27/make/apf27.mk

