#specify application basename 
EXEC=app

#search for soure code (C & assembler files)
SRCS=$(wildcard *.c)
ASRC=$(wildcard *.s)

#specify additional libraries to be generated
LIBDIRS=libs

#specifiy additional packages to build
EXTRADIRS=

# Includee the standard APF27 makefile for the microprocessor labs 
include $(LMIBASE)/apf27/make/apf27.mk

